# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from MySlider import MySlider


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 800)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resource/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget#Form {\n"
"    background-color: #1E1E20;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_menu = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_menu.sizePolicy().hasHeightForWidth())
        self.frame_menu.setSizePolicy(sizePolicy)
        self.frame_menu.setMinimumSize(QtCore.QSize(240, 0))
        self.frame_menu.setMaximumSize(QtCore.QSize(240, 16777215))
        self.frame_menu.setStyleSheet("#frame_menu {\n"
"    background-color: #161616;\n"
"}")
        self.frame_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menu.setObjectName("frame_menu")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_menu)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.frame_basic_op = QtWidgets.QFrame(self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_basic_op.sizePolicy().hasHeightForWidth())
        self.frame_basic_op.setSizePolicy(sizePolicy)
        self.frame_basic_op.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_basic_op.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_basic_op.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_basic_op.setObjectName("frame_basic_op")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_basic_op)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_save = QtWidgets.QPushButton(self.frame_basic_op)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_save.setMaximumSize(QtCore.QSize(180, 50))
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setStyleSheet("#btn_save {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}\n"
"\n"
"#btn_save::hover {\n"
"    background-color: #00F5D0;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}\n"
"\n"
"#btn_save::pressed {\n"
"    background-color: #00F5D0;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resource/save(D2F6EE).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon1)
        self.btn_save.setIconSize(QtCore.QSize(30, 30))
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_2.addWidget(self.btn_save, 4, 0, 1, 1)
        self.btn_import = QtWidgets.QPushButton(self.frame_basic_op)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        self.btn_import.setMinimumSize(QtCore.QSize(180, 50))
        self.btn_import.setMaximumSize(QtCore.QSize(180, 50))
        self.btn_import.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_import.setStyleSheet("#btn_import {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}\n"
"\n"
"#btn_import::hover {\n"
"    background-color: #00F5D0;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}\n"
"\n"
"#btn_import::pressed {\n"
"    background-color: #00F5D0;\n"
"    border-radius: 25px;\n"
"    color: #D2F6EE;\n"
"    font-size: 20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resource/import(D2F6EE).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_import.setIcon(icon2)
        self.btn_import.setIconSize(QtCore.QSize(30, 30))
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_2.addWidget(self.btn_import, 2, 0, 1, 1)
        self.lb_tip_basic = QtWidgets.QLabel(self.frame_basic_op)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_tip_basic.sizePolicy().hasHeightForWidth())
        self.lb_tip_basic.setSizePolicy(sizePolicy)
        self.lb_tip_basic.setMinimumSize(QtCore.QSize(140, 30))
        self.lb_tip_basic.setStyleSheet("#lb_tip_basic {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        self.lb_tip_basic.setObjectName("lb_tip_basic")
        self.gridLayout_2.addWidget(self.lb_tip_basic, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_basic_op, 1, 0, 1, 1)
        self.frame_select = QtWidgets.QFrame(self.frame_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_select.sizePolicy().hasHeightForWidth())
        self.frame_select.setSizePolicy(sizePolicy)
        self.frame_select.setMinimumSize(QtCore.QSize(0, 190))
        self.frame_select.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_select.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_select.setObjectName("frame_select")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_select)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem4 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem4, 2, 0, 1, 1)
        self.lb_tip_select = QtWidgets.QLabel(self.frame_select)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_tip_select.sizePolicy().hasHeightForWidth())
        self.lb_tip_select.setSizePolicy(sizePolicy)
        self.lb_tip_select.setMinimumSize(QtCore.QSize(140, 30))
        self.lb_tip_select.setStyleSheet("#lb_tip_select {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        self.lb_tip_select.setObjectName("lb_tip_select")
        self.gridLayout_4.addWidget(self.lb_tip_select, 0, 0, 1, 1)
        self.tbtn_swap = QtWidgets.QToolButton(self.frame_select)
        self.tbtn_swap.setMinimumSize(QtCore.QSize(180, 50))
        self.tbtn_swap.setMaximumSize(QtCore.QSize(180, 50))
        self.tbtn_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbtn_swap.setStyleSheet("#tbtn_swap {\n"
"    background-color: #1B1B1B;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#tbtn_swap::hover {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#tbtn_swap::pressed, #tbtn_swap::checked {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/resource/swap.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_swap.setIcon(icon3)
        self.tbtn_swap.setIconSize(QtCore.QSize(30, 30))
        self.tbtn_swap.setCheckable(True)
        self.tbtn_swap.setChecked(True)
        self.tbtn_swap.setAutoExclusive(True)
        self.tbtn_swap.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.tbtn_swap.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbtn_swap.setAutoRaise(False)
        self.tbtn_swap.setObjectName("tbtn_swap")
        self.gridLayout_4.addWidget(self.tbtn_swap, 1, 0, 1, 1)
        self.tbtn_detection = QtWidgets.QToolButton(self.frame_select)
        self.tbtn_detection.setMinimumSize(QtCore.QSize(180, 50))
        self.tbtn_detection.setMaximumSize(QtCore.QSize(180, 50))
        self.tbtn_detection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbtn_detection.setStyleSheet("#tbtn_detection {\n"
"    background-color: #1B1B1B;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#tbtn_detection::hover {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}\n"
"\n"
"#tbtn_detection::pressed, #tbtn_detection::checked {\n"
"    background-color: #1ECE9E;\n"
"    border-radius: 10px;\n"
"    color: #D2F6EE;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    font-size: 20px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/resource/recognize(D2F6EE).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbtn_detection.setIcon(icon4)
        self.tbtn_detection.setIconSize(QtCore.QSize(30, 30))
        self.tbtn_detection.setCheckable(True)
        self.tbtn_detection.setChecked(False)
        self.tbtn_detection.setAutoExclusive(True)
        self.tbtn_detection.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.tbtn_detection.setObjectName("tbtn_detection")
        self.gridLayout_4.addWidget(self.tbtn_detection, 3, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_select, 3, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_menu)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setStyleSheet("#stackedWidget{\n"
"    background:transparent;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_swap = QtWidgets.QWidget()
        self.page_swap.setObjectName("page_swap")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_swap)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_tips_swap = QtWidgets.QFrame(self.page_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tips_swap.sizePolicy().hasHeightForWidth())
        self.frame_tips_swap.setSizePolicy(sizePolicy)
        self.frame_tips_swap.setMinimumSize(QtCore.QSize(615, 60))
        self.frame_tips_swap.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_tips_swap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tips_swap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tips_swap.setObjectName("frame_tips_swap")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_tips_swap)
        self.horizontalLayout_3.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lb_swap = QtWidgets.QLabel(self.frame_tips_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_swap.sizePolicy().hasHeightForWidth())
        self.lb_swap.setSizePolicy(sizePolicy)
        self.lb_swap.setMinimumSize(QtCore.QSize(170, 36))
        self.lb_swap.setMaximumSize(QtCore.QSize(170, 36))
        self.lb_swap.setStyleSheet("#lb_swap{\n"
"    font-size: 28px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #FFFFFF;\n"
"}")
        self.lb_swap.setObjectName("lb_swap")
        self.horizontalLayout_3.addWidget(self.lb_swap)
        self.lb_tip_swap = QtWidgets.QLabel(self.frame_tips_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_tip_swap.sizePolicy().hasHeightForWidth())
        self.lb_tip_swap.setSizePolicy(sizePolicy)
        self.lb_tip_swap.setMinimumSize(QtCore.QSize(0, 36))
        self.lb_tip_swap.setMaximumSize(QtCore.QSize(16777215, 36))
        self.lb_tip_swap.setStyleSheet("#lb_tip_swap {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        self.lb_tip_swap.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_tip_swap.setObjectName("lb_tip_swap")
        self.horizontalLayout_3.addWidget(self.lb_tip_swap)
        self.btn_swap = QtWidgets.QPushButton(self.frame_tips_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_swap.sizePolicy().hasHeightForWidth())
        self.btn_swap.setSizePolicy(sizePolicy)
        self.btn_swap.setMinimumSize(QtCore.QSize(160, 36))
        self.btn_swap.setMaximumSize(QtCore.QSize(160, 40))
        self.btn_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_swap.setStyleSheet("#btn_swap {\n"
"    background-color: #548AF7;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}\n"
"\n"
"#btn_swap::hover {\n"
"    background-color: #549AFF;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}\n"
"\n"
"#btn_swap::pressed {\n"
"    background-color: #549AFF;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/resource/flash(#D2F6EE).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_swap.setIcon(icon5)
        self.btn_swap.setIconSize(QtCore.QSize(25, 25))
        self.btn_swap.setObjectName("btn_swap")
        self.horizontalLayout_3.addWidget(self.btn_swap)
        self.gridLayout_3.addWidget(self.frame_tips_swap, 0, 0, 1, 1)
        self.frame_video_swap = QtWidgets.QFrame(self.page_swap)
        self.frame_video_swap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_swap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_swap.setObjectName("frame_video_swap")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_video_swap)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setHorizontalSpacing(0)
        self.gridLayout_5.setVerticalSpacing(7)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_video_op_swap = QtWidgets.QFrame(self.frame_video_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_video_op_swap.sizePolicy().hasHeightForWidth())
        self.frame_video_op_swap.setSizePolicy(sizePolicy)
        self.frame_video_op_swap.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_video_op_swap.setMaximumSize(QtCore.QSize(260, 40))
        self.frame_video_op_swap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_op_swap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_op_swap.setObjectName("frame_video_op_swap")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_video_op_swap)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_backward_swap = QtWidgets.QPushButton(self.frame_video_op_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backward_swap.sizePolicy().hasHeightForWidth())
        self.btn_backward_swap.setSizePolicy(sizePolicy)
        self.btn_backward_swap.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_backward_swap.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_backward_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_backward_swap.setStyleSheet("#btn_backward_swap {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_backward_swap::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_backward_swap::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_backward_swap.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/resource/backward(#1ECE9E).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_backward_swap.setIcon(icon6)
        self.btn_backward_swap.setIconSize(QtCore.QSize(30, 30))
        self.btn_backward_swap.setFlat(True)
        self.btn_backward_swap.setObjectName("btn_backward_swap")
        self.horizontalLayout_2.addWidget(self.btn_backward_swap)
        self.btn_play_pause_swap = QtWidgets.QPushButton(self.frame_video_op_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_pause_swap.sizePolicy().hasHeightForWidth())
        self.btn_play_pause_swap.setSizePolicy(sizePolicy)
        self.btn_play_pause_swap.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_play_pause_swap.setMaximumSize(QtCore.QSize(60, 30))
        self.btn_play_pause_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play_pause_swap.setStyleSheet("#btn_play_pause_swap {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_play_pause_swap::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_play_pause_swap::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_play_pause_swap.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/resource/play(#1ECE9E).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_play_pause_swap.setIcon(icon7)
        self.btn_play_pause_swap.setIconSize(QtCore.QSize(30, 30))
        self.btn_play_pause_swap.setFlat(True)
        self.btn_play_pause_swap.setObjectName("btn_play_pause_swap")
        self.horizontalLayout_2.addWidget(self.btn_play_pause_swap)
        self.btn_forward_swap = QtWidgets.QPushButton(self.frame_video_op_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_forward_swap.sizePolicy().hasHeightForWidth())
        self.btn_forward_swap.setSizePolicy(sizePolicy)
        self.btn_forward_swap.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_forward_swap.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_forward_swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_forward_swap.setStyleSheet("#btn_forward_swap {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_forward_swap::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_forward_swap::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_forward_swap.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/resource/forward(#1ECE9E).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_forward_swap.setIcon(icon8)
        self.btn_forward_swap.setIconSize(QtCore.QSize(30, 30))
        self.btn_forward_swap.setFlat(True)
        self.btn_forward_swap.setObjectName("btn_forward_swap")
        self.horizontalLayout_2.addWidget(self.btn_forward_swap)
        self.gridLayout_5.addWidget(self.frame_video_op_swap, 2, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem5, 2, 0, 1, 1)
        self.lb_editable_swap = QtWidgets.QLabel(self.frame_video_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_editable_swap.sizePolicy().hasHeightForWidth())
        self.lb_editable_swap.setSizePolicy(sizePolicy)
        self.lb_editable_swap.setMinimumSize(QtCore.QSize(162, 24))
        self.lb_editable_swap.setMaximumSize(QtCore.QSize(162, 24))
        self.lb_editable_swap.setStyleSheet("#lb_editable_swap {\n"
"    color: #F8D714;\n"
"    font-size: 18px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        self.lb_editable_swap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_editable_swap.setObjectName("lb_editable_swap")
        self.gridLayout_5.addWidget(self.lb_editable_swap, 2, 5, 1, 1)
        self.lb_space_swap = QtWidgets.QLabel(self.frame_video_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_space_swap.sizePolicy().hasHeightForWidth())
        self.lb_space_swap.setSizePolicy(sizePolicy)
        self.lb_space_swap.setMinimumSize(QtCore.QSize(162, 24))
        self.lb_space_swap.setMaximumSize(QtCore.QSize(162, 24))
        self.lb_space_swap.setStyleSheet("#lb_space_swap {\n"
"    background: transparent;\n"
"}")
        self.lb_space_swap.setText("")
        self.lb_space_swap.setObjectName("lb_space_swap")
        self.gridLayout_5.addWidget(self.lb_space_swap, 2, 1, 1, 1)
        self.widget_video_swap = QVideoWidget(self.frame_video_swap)
        self.widget_video_swap.setMinimumSize(QtCore.QSize(320, 180))
        self.widget_video_swap.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_video_swap.setStyleSheet("#widget_video_swap {\n"
"    background-color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 5px;\n"
"}")
        self.widget_video_swap.setObjectName("widget_video_swap")
        self.gridLayout_5.addWidget(self.widget_video_swap, 0, 0, 1, 7)
        self.frame_slider_time_swap = QtWidgets.QFrame(self.frame_video_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_slider_time_swap.sizePolicy().hasHeightForWidth())
        self.frame_slider_time_swap.setSizePolicy(sizePolicy)
        self.frame_slider_time_swap.setMinimumSize(QtCore.QSize(0, 22))
        self.frame_slider_time_swap.setMaximumSize(QtCore.QSize(16777215, 22))
        self.frame_slider_time_swap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider_time_swap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider_time_swap.setObjectName("frame_slider_time_swap")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_slider_time_swap)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.slider_video_swap = MySlider(self.frame_slider_time_swap)
        self.slider_video_swap.setStyleSheet("/*槽*/\n"
"#slider_video_swap::groove:horizontal {\n"
"    border: 1px solid #1ECE9E;\n"
"    border-radius:2px;\n"
"    height: 4px;\n"
"    left: 1px; right: 1px;\n"
"}\n"
"\n"
"/*已经划过的部分*/\n"
"#slider_video_swap::sub-page:horizontal{\n"
"    background: #1ECE9E;\n"
"}")
        self.slider_video_swap.setTracking(True)
        self.slider_video_swap.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video_swap.setObjectName("slider_video_swap")
        self.horizontalLayout_6.addWidget(self.slider_video_swap)
        self.frame_time_swap = QtWidgets.QFrame(self.frame_slider_time_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_time_swap.sizePolicy().hasHeightForWidth())
        self.frame_time_swap.setSizePolicy(sizePolicy)
        self.frame_time_swap.setMinimumSize(QtCore.QSize(135, 22))
        self.frame_time_swap.setMaximumSize(QtCore.QSize(135, 22))
        self.frame_time_swap.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time_swap.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time_swap.setObjectName("frame_time_swap")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_time_swap)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lb_cur_time_swap = QtWidgets.QLabel(self.frame_time_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_cur_time_swap.sizePolicy().hasHeightForWidth())
        self.lb_cur_time_swap.setSizePolicy(sizePolicy)
        self.lb_cur_time_swap.setMinimumSize(QtCore.QSize(54, 18))
        self.lb_cur_time_swap.setMaximumSize(QtCore.QSize(54, 18))
        self.lb_cur_time_swap.setStyleSheet("#lb_cur_time_swap {\n"
"    color: #FFFFFF;\n"
"    font-size: 18px;\n"
"}")
        self.lb_cur_time_swap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_cur_time_swap.setObjectName("lb_cur_time_swap")
        self.horizontalLayout_5.addWidget(self.lb_cur_time_swap)
        self.lb_delimiter_swap = QtWidgets.QLabel(self.frame_time_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_delimiter_swap.sizePolicy().hasHeightForWidth())
        self.lb_delimiter_swap.setSizePolicy(sizePolicy)
        self.lb_delimiter_swap.setMinimumSize(QtCore.QSize(27, 22))
        self.lb_delimiter_swap.setMaximumSize(QtCore.QSize(27, 22))
        self.lb_delimiter_swap.setStyleSheet("#lb_delimiter_swap {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"}")
        self.lb_delimiter_swap.setObjectName("lb_delimiter_swap")
        self.horizontalLayout_5.addWidget(self.lb_delimiter_swap)
        self.lb_max_time_swap = QtWidgets.QLabel(self.frame_time_swap)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_max_time_swap.sizePolicy().hasHeightForWidth())
        self.lb_max_time_swap.setSizePolicy(sizePolicy)
        self.lb_max_time_swap.setMinimumSize(QtCore.QSize(54, 18))
        self.lb_max_time_swap.setMaximumSize(QtCore.QSize(54, 18))
        self.lb_max_time_swap.setStyleSheet("#lb_max_time_swap {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"}")
        self.lb_max_time_swap.setObjectName("lb_max_time_swap")
        self.horizontalLayout_5.addWidget(self.lb_max_time_swap)
        self.horizontalLayout_6.addWidget(self.frame_time_swap)
        self.gridLayout_5.addWidget(self.frame_slider_time_swap, 1, 0, 1, 7)
        spacerItem6 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 2, 6, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 2, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 2, 4, 1, 1)
        self.gridLayout_3.addWidget(self.frame_video_swap, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_swap)
        self.page_detection = QtWidgets.QWidget()
        self.page_detection.setObjectName("page_detection")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_detection)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.frame_tips_detection = QtWidgets.QFrame(self.page_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_tips_detection.sizePolicy().hasHeightForWidth())
        self.frame_tips_detection.setSizePolicy(sizePolicy)
        self.frame_tips_detection.setMinimumSize(QtCore.QSize(615, 60))
        self.frame_tips_detection.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_tips_detection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tips_detection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tips_detection.setObjectName("frame_tips_detection")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_tips_detection)
        self.horizontalLayout_4.setContentsMargins(11, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lb_detection = QtWidgets.QLabel(self.frame_tips_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_detection.sizePolicy().hasHeightForWidth())
        self.lb_detection.setSizePolicy(sizePolicy)
        self.lb_detection.setMinimumSize(QtCore.QSize(170, 36))
        self.lb_detection.setMaximumSize(QtCore.QSize(170, 36))
        self.lb_detection.setStyleSheet("#lb_detection {\n"
"    font-size: 28px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #FFFFFF;\n"
"}")
        self.lb_detection.setObjectName("lb_detection")
        self.horizontalLayout_4.addWidget(self.lb_detection)
        self.lb_tip_detection = QtWidgets.QLabel(self.frame_tips_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_tip_detection.sizePolicy().hasHeightForWidth())
        self.lb_tip_detection.setSizePolicy(sizePolicy)
        self.lb_tip_detection.setMinimumSize(QtCore.QSize(0, 36))
        self.lb_tip_detection.setMaximumSize(QtCore.QSize(16777215, 36))
        self.lb_tip_detection.setStyleSheet("#lb_tip_detection {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"}")
        self.lb_tip_detection.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.lb_tip_detection.setObjectName("lb_tip_detection")
        self.horizontalLayout_4.addWidget(self.lb_tip_detection)
        self.btn_detection = QtWidgets.QPushButton(self.frame_tips_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_detection.sizePolicy().hasHeightForWidth())
        self.btn_detection.setSizePolicy(sizePolicy)
        self.btn_detection.setMinimumSize(QtCore.QSize(160, 36))
        self.btn_detection.setMaximumSize(QtCore.QSize(160, 40))
        self.btn_detection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_detection.setStyleSheet("#btn_detection {\n"
"    background-color: #548AF7;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}\n"
"\n"
"#btn_detection::hover {\n"
"    background-color: #549AFF;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}\n"
"\n"
"#btn_detection::pressed {\n"
"    background-color: #549AFF;\n"
"    border-radius: 18px;\n"
"    font-size:20px;\n"
"    font-family: \'MicroSoft YaHei\';\n"
"    color: #D2F6EE;\n"
"}")
        self.btn_detection.setIcon(icon5)
        self.btn_detection.setIconSize(QtCore.QSize(25, 25))
        self.btn_detection.setObjectName("btn_detection")
        self.horizontalLayout_4.addWidget(self.btn_detection)
        self.gridLayout_7.addWidget(self.frame_tips_detection, 0, 0, 1, 1)
        self.frame_video_detection = QtWidgets.QFrame(self.page_detection)
        self.frame_video_detection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_detection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_detection.setObjectName("frame_video_detection")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_video_detection)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setVerticalSpacing(7)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem9, 2, 1, 1, 1)
        self.widget_video_detection = QVideoWidget(self.frame_video_detection)
        self.widget_video_detection.setMinimumSize(QtCore.QSize(320, 180))
        self.widget_video_detection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_video_detection.setStyleSheet("#widget_video_detection {\n"
"    background-color: #000000;\n"
"    border: 1px solid #000000;\n"
"    border-radius: 5px;\n"
"}")
        self.widget_video_detection.setObjectName("widget_video_detection")
        self.gridLayout_6.addWidget(self.widget_video_detection, 0, 0, 1, 5)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem10, 2, 3, 1, 1)
        self.frame_video_op_detection = QtWidgets.QFrame(self.frame_video_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_video_op_detection.sizePolicy().hasHeightForWidth())
        self.frame_video_op_detection.setSizePolicy(sizePolicy)
        self.frame_video_op_detection.setMinimumSize(QtCore.QSize(200, 40))
        self.frame_video_op_detection.setMaximumSize(QtCore.QSize(260, 40))
        self.frame_video_op_detection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_video_op_detection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_video_op_detection.setObjectName("frame_video_op_detection")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_video_op_detection)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_backward_detection = QtWidgets.QPushButton(self.frame_video_op_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_backward_detection.sizePolicy().hasHeightForWidth())
        self.btn_backward_detection.setSizePolicy(sizePolicy)
        self.btn_backward_detection.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_backward_detection.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_backward_detection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_backward_detection.setStyleSheet("#btn_backward_detection {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_backward_detection::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_backward_detection::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_backward_detection.setText("")
        self.btn_backward_detection.setIcon(icon6)
        self.btn_backward_detection.setIconSize(QtCore.QSize(30, 30))
        self.btn_backward_detection.setFlat(True)
        self.btn_backward_detection.setObjectName("btn_backward_detection")
        self.horizontalLayout_7.addWidget(self.btn_backward_detection)
        self.btn_play_pause_detection = QtWidgets.QPushButton(self.frame_video_op_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play_pause_detection.sizePolicy().hasHeightForWidth())
        self.btn_play_pause_detection.setSizePolicy(sizePolicy)
        self.btn_play_pause_detection.setMinimumSize(QtCore.QSize(60, 30))
        self.btn_play_pause_detection.setMaximumSize(QtCore.QSize(60, 30))
        self.btn_play_pause_detection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_play_pause_detection.setStyleSheet("#btn_play_pause_detection {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_play_pause_detection::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_play_pause_detection::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_play_pause_detection.setText("")
        self.btn_play_pause_detection.setIcon(icon7)
        self.btn_play_pause_detection.setIconSize(QtCore.QSize(30, 30))
        self.btn_play_pause_detection.setFlat(True)
        self.btn_play_pause_detection.setObjectName("btn_play_pause_detection")
        self.horizontalLayout_7.addWidget(self.btn_play_pause_detection)
        self.btn_forward_detection = QtWidgets.QPushButton(self.frame_video_op_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_forward_detection.sizePolicy().hasHeightForWidth())
        self.btn_forward_detection.setSizePolicy(sizePolicy)
        self.btn_forward_detection.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_forward_detection.setMaximumSize(QtCore.QSize(30, 30))
        self.btn_forward_detection.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_forward_detection.setStyleSheet("#btn_forward_detection {\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#btn_forward_detection::hover {\n"
"    background-color: #282828;\n"
"}\n"
"\n"
"#btn_forward_detection::pressed {\n"
"    background-color: #282828;\n"
"}")
        self.btn_forward_detection.setText("")
        self.btn_forward_detection.setIcon(icon8)
        self.btn_forward_detection.setIconSize(QtCore.QSize(30, 30))
        self.btn_forward_detection.setFlat(True)
        self.btn_forward_detection.setObjectName("btn_forward_detection")
        self.horizontalLayout_7.addWidget(self.btn_forward_detection)
        self.gridLayout_6.addWidget(self.frame_video_op_detection, 2, 2, 1, 1)
        self.frame_slider_time_detection = QtWidgets.QFrame(self.frame_video_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_slider_time_detection.sizePolicy().hasHeightForWidth())
        self.frame_slider_time_detection.setSizePolicy(sizePolicy)
        self.frame_slider_time_detection.setMinimumSize(QtCore.QSize(0, 22))
        self.frame_slider_time_detection.setMaximumSize(QtCore.QSize(16777215, 22))
        self.frame_slider_time_detection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_slider_time_detection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_slider_time_detection.setObjectName("frame_slider_time_detection")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_slider_time_detection)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.slider_video_detection = MySlider(self.frame_slider_time_detection)
        self.slider_video_detection.setStyleSheet("/*槽*/\n"
"#slider_video_detection::groove:horizontal {\n"
"    border: 1px solid #1ECE9E;\n"
"    border-radius:2px;\n"
"    height: 4px;\n"
"    left: 1px; right: 1px;\n"
"}\n"
"\n"
"/*已经划过的部分*/\n"
"#slider_video_detection::sub-page:horizontal{\n"
"    background: #1ECE9E;\n"
"}")
        self.slider_video_detection.setTracking(True)
        self.slider_video_detection.setOrientation(QtCore.Qt.Horizontal)
        self.slider_video_detection.setObjectName("slider_video_detection")
        self.horizontalLayout_8.addWidget(self.slider_video_detection)
        self.frame_time_detection = QtWidgets.QFrame(self.frame_slider_time_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_time_detection.sizePolicy().hasHeightForWidth())
        self.frame_time_detection.setSizePolicy(sizePolicy)
        self.frame_time_detection.setMinimumSize(QtCore.QSize(135, 22))
        self.frame_time_detection.setMaximumSize(QtCore.QSize(135, 22))
        self.frame_time_detection.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_time_detection.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_time_detection.setObjectName("frame_time_detection")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_time_detection)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lb_cur_time_detection = QtWidgets.QLabel(self.frame_time_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_cur_time_detection.sizePolicy().hasHeightForWidth())
        self.lb_cur_time_detection.setSizePolicy(sizePolicy)
        self.lb_cur_time_detection.setMinimumSize(QtCore.QSize(54, 18))
        self.lb_cur_time_detection.setMaximumSize(QtCore.QSize(54, 18))
        self.lb_cur_time_detection.setStyleSheet("#lb_cur_time_detection {\n"
"    color: #FFFFFF;\n"
"    font-size: 18px;\n"
"}")
        self.lb_cur_time_detection.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_cur_time_detection.setObjectName("lb_cur_time_detection")
        self.horizontalLayout_9.addWidget(self.lb_cur_time_detection)
        self.lb_delimiter_detection = QtWidgets.QLabel(self.frame_time_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_delimiter_detection.sizePolicy().hasHeightForWidth())
        self.lb_delimiter_detection.setSizePolicy(sizePolicy)
        self.lb_delimiter_detection.setMinimumSize(QtCore.QSize(27, 22))
        self.lb_delimiter_detection.setMaximumSize(QtCore.QSize(27, 22))
        self.lb_delimiter_detection.setStyleSheet("#lb_delimiter_detection {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"}")
        self.lb_delimiter_detection.setObjectName("lb_delimiter_detection")
        self.horizontalLayout_9.addWidget(self.lb_delimiter_detection)
        self.lb_max_time_detection = QtWidgets.QLabel(self.frame_time_detection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_max_time_detection.sizePolicy().hasHeightForWidth())
        self.lb_max_time_detection.setSizePolicy(sizePolicy)
        self.lb_max_time_detection.setMinimumSize(QtCore.QSize(54, 18))
        self.lb_max_time_detection.setMaximumSize(QtCore.QSize(54, 18))
        self.lb_max_time_detection.setStyleSheet("#lb_max_time_detection {\n"
"    color: #828282;\n"
"    font-size: 18px;\n"
"}")
        self.lb_max_time_detection.setObjectName("lb_max_time_detection")
        self.horizontalLayout_9.addWidget(self.lb_max_time_detection)
        self.horizontalLayout_8.addWidget(self.frame_time_detection)
        self.gridLayout_6.addWidget(self.frame_slider_time_detection, 1, 0, 1, 5)
        self.gridLayout_7.addWidget(self.frame_video_detection, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_detection)
        self.horizontalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "车牌隐私保护及车牌篡改检测系统"))
        self.btn_save.setText(_translate("Form", "保存结果"))
        self.btn_import.setText(_translate("Form", "导入视频"))
        self.lb_tip_basic.setText(_translate("Form", "基础操作"))
        self.lb_tip_select.setText(_translate("Form", "功能选择"))
        self.tbtn_swap.setText(_translate("Form", "车牌随机替换"))
        self.tbtn_detection.setText(_translate("Form", "车牌篡改检测"))
        self.lb_swap.setText(_translate("Form", "车牌随机替换"))
        self.lb_tip_swap.setText(_translate("Form", "在随机替换完毕后可以单击车牌选取不想替换的车牌"))
        self.btn_swap.setText(_translate("Form", "一键替换"))
        self.btn_backward_swap.setToolTip(_translate("Form", "向前1秒"))
        self.btn_backward_swap.setShortcut(_translate("Form", "Left"))
        self.btn_play_pause_swap.setToolTip(_translate("Form", "播放/暂停"))
        self.btn_play_pause_swap.setShortcut(_translate("Form", "Space"))
        self.btn_forward_swap.setToolTip(_translate("Form", "向后1秒"))
        self.btn_forward_swap.setShortcut(_translate("Form", "Right"))
        self.lb_editable_swap.setText(_translate("Form", ""))
        self.lb_cur_time_swap.setText(_translate("Form", "00:00"))
        self.lb_delimiter_swap.setText(_translate("Form", " / "))
        self.lb_max_time_swap.setText(_translate("Form", "00:00"))
        self.lb_detection.setText(_translate("Form", "车牌篡改检测"))
        self.lb_tip_detection.setText(_translate("Form", "涉嫌电脑合成的车牌将在视频中标出"))
        self.btn_detection.setText(_translate("Form", "一键检测"))
        self.btn_backward_detection.setToolTip(_translate("Form", "向前1秒"))
        self.btn_backward_detection.setShortcut(_translate("Form", "Left"))
        self.btn_play_pause_detection.setToolTip(_translate("Form", "播放/暂停"))
        self.btn_play_pause_detection.setShortcut(_translate("Form", "Space"))
        self.btn_forward_detection.setToolTip(_translate("Form", "向后1秒"))
        self.btn_forward_detection.setShortcut(_translate("Form", "Right"))
        self.lb_cur_time_detection.setText(_translate("Form", "00:00"))
        self.lb_delimiter_detection.setText(_translate("Form", " / "))
        self.lb_max_time_detection.setText(_translate("Form", "00:00"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
import resource_rc
